### PR TITLE
feat: Remove the service worker

### PR DESCRIPTION
**Pull request by bitdivine**
# Motivation
The service worker has found a new home in the ic monorepo.

# Changes
- Removed the service worker, its related files and references to it.
- Given that the service worker was the only entry under `/apps` this also removes the lerna entry for `/apps/*`.

### CODE REVIEW

**Comment by nomeata** [comment]
Will it be included in the code dump at https://github.com/dfinity/ic? This useful for us outsiders who want to know how things work (and try to break things, see https://forum.dfinity.org/t/a-single-node-provider-might-be-able-to-take-over-internet-identities-it-seems/7464, which maybe needs more eyes, in particular your’s, Max :-))

**Comment by bitdivine** [comment]
Hello, good to see you again!  Apart from "soon" I don't know the timeline for open sourcing.  I have moved this into the ic repo though so I expect that it will be included in the code you will get to pummel. Here it will be available in git history.  I am not sure that it would be a good idea to keep it at the head of master, as it would confuse people looking for the one true source.

**Review by krpeacock — APPROVED** [review]

**Comment by bitdivine** [comment]
I do find it rather thrilling that I am getting review comments from people outside, in the wide world.  The dream is coming true.  Next step:  PRs are merged or blocked by community vote.

**Comment by nomeata** [comment]
> I expect that it will be included in the code you will get to pummel. 

Not if not explicitly whitelisted in the `opensource` tool. Maybe ping the right people so that happens?

**Comment by nomeata** [comment]
The Haskell GitHub action installer has changed. See the agent repos for how they fixed that, if you want.

**Comment by bitdivine** [comment]
It seems as if negative code is all I need for ghc.  Removing stub code and merging.

**Comment by bitdivine** [comment]
I have asked for the code to be included in the open-sourced ic codebase.

**Comment by krpeacock** [comment]
I'm going to hold off on merging the removal until we get confirmation that its new home can be made public. For the record though, the serviceworker will not be maintained in this repository any further

**Comment by frederikrothenberger** [comment]
@krpeacock: Can we revive this PR and do the merge now (as the ic repo is now public)?

**Comment by krpeacock** [comment]
> @krpeacock: Can we revive this PR and do the merge now (as the ic repo is now public)?

Yes we can. Service worker is now located here: https://github.com/dfinity/ic/tree/master/typescript%2Fservice-worker

**Pull request merged**
