### PR TITLE
feat: Use full IC Management IDL

### PR DESCRIPTION
**Pull request by megrogan**

### CODE REVIEW

**Comment by megrogan** [comment]
@krpeacock I have pushed 2 commits to my [branch](https://github.com/megrogan/agent-js/tree/full-management-IDL) but seems like there is a github issue because the PR has not been updated. I will create a new PR.

**Comment by megrogan** [comment]
I think this was because my fork was still private whereas this repo has since become public. I have now made my fork public but the PR has not updated yet...

**Comment by megrogan** [comment]
This is my issue:
https://stackoverflow.com/questions/36225381/reattach-a-detached-fork-in-github

I am following the 2nd answer and contacting github support...

**Comment by megrogan** [comment]
They have re-attached my fork

**Comment by krpeacock** [comment]
What a weird state to get into!

**Comment by megrogan** [comment]
I needed to push another commit (just removed a full-top from a comment!) and that seems to have finally wired it back up such that the other commits since my original one have now been applied to the PR too!

**Comment by megrogan** [comment]
Argh! Failing e2e tests. Will investigate

**Comment by hansl** [comment]
@krpeacock Can we get this closed? I don't think this is being worked on.

**Review by hansl — APPROVED** [review]

**Comment by krpeacock** [comment]
@megrogan I can't update your PR, but making this change to label the method as an `ActorMethod` will get the final test passing

https://github.com/dfinity/agent-js/blob/kyle/ic-management/e2e/node/basic/basic.test.ts#L50

**Comment by krpeacock** [comment]
That does raise a separate issue that we ought to figure out how to get `ActorMethod` typing to automatically apply to actors instantiated with generated types

**Review by krpeacock — APPROVED** [review]

**Pull request merged**
